import { Course } from "../Types/course_type"

export const COURSES: Course[] = [
  {
    id: 1,
    title: "Advanced React Patterns & Architecture",
    instructor: "Sarah Chen",
    category: "Frontend Development",
    progress: 68,
    totalLessons: 42,
    completedLessons: 28,
    accent: "#6EE7B7",
    badge: "In Progress",
    lastAccessed: "2 hours ago",
    modules: [
      {
        id: 1,
        title: "Foundations & Core Concepts",
        description: "Revisiting the essentials with a deeper lens.",
        lessons: [
          { id: 1, title: "Component Composition Deep Dive", duration: "18 min", type: "video", completed: true },
          { id: 2, title: "Understanding Reconciliation", duration: "22 min", type: "video", completed: true },
          { id: 3, title: "Render Optimization Fundamentals", duration: "12 min", type: "reading", completed: true },
          { id: 4, title: "Module Quiz", duration: "10 min", type: "quiz", completed: true },
        ],
      },
      {
        id: 2,
        title: "Advanced Hooks Patterns",
        description: "Custom hooks, composition patterns, and edge cases.",
        lessons: [
          { id: 5, title: "Building Custom Hooks", duration: "25 min", type: "video", completed: true },
          { id: 6, title: "useReducer vs useState", duration: "20 min", type: "video", completed: true },
          { id: 7, title: "The useMemo & useCallback Trap", duration: "15 min", type: "reading", completed: false },
          { id: 8, title: "Practical Hook Assignment", duration: "30 min", type: "assignment", completed: false },
        ],
      },
      {
        id: 3,
        title: "State Management Architecture",
        description: "Patterns for scalable, maintainable state.",
        lessons: [
          { id: 9, title: "Context API at Scale", duration: "28 min", type: "video", completed: false },
          { id: 10, title: "Zustand & Jotai Overview", duration: "20 min", type: "video", completed: false },
          { id: 11, title: "State Machines with XState", duration: "35 min", type: "video", completed: false },
          { id: 12, title: "Architecture Assessment", duration: "45 min", type: "assignment", completed: false },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "UI/UX Design Systems from Scratch",
    instructor: "Marcus Webb",
    category: "Design",
    progress: 32,
    totalLessons: 36,
    completedLessons: 11,
    accent: "#FCA5A5",
    badge: "In Progress",
    lastAccessed: "Yesterday",
    modules: [
      {
        id: 1,
        title: "Design System Foundations",
        description: "Tokens, principles, and system thinking.",
        lessons: [
          { id: 1, title: "What Makes a Design System", duration: "20 min", type: "video", completed: true },
          { id: 2, title: "Design Tokens Explained", duration: "16 min", type: "reading", completed: true },
          { id: 3, title: "Color System Architecture", duration: "24 min", type: "video", completed: true },
          { id: 4, title: "Typography Scales & Hierarchy", duration: "18 min", type: "video", completed: false },
        ],
      },
      {
        id: 2,
        title: "Component Library Design",
        description: "Building reusable, accessible components.",
        lessons: [
          { id: 5, title: "Atomic Design Methodology", duration: "22 min", type: "video", completed: false },
          { id: 6, title: "Component Variants & States", duration: "30 min", type: "video", completed: false },
          { id: 7, title: "Accessibility in Components", duration: "25 min", type: "reading", completed: false },
        ],
      },
      {
        id: 3,
        title: "Handoff & Documentation",
        description: "From design to production-ready specs.",
        lessons: [
          { id: 8, title: "Figma Tokens & Dev Mode", duration: "28 min", type: "video", completed: false },
          { id: 9, title: "Writing Component Documentation", duration: "20 min", type: "assignment", completed: false },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Data Structures & Algorithms Mastery",
    instructor: "Dr. Aisha Patel",
    category: "Computer Science",
    progress: 100,
    totalLessons: 54,
    completedLessons: 54,
    accent: "#C4B5FD",
    badge: "Completed",
    lastAccessed: "3 days ago",
    modules: [
      {
        id: 1,
        title: "Arrays, Strings & Hashing",
        description: "Fundamental structures with real interview problems.",
        lessons: [
          { id: 1, title: "Array Manipulation Techniques", duration: "30 min", type: "video", completed: true },
          { id: 2, title: "Two Pointer & Sliding Window", duration: "35 min", type: "video", completed: true },
          { id: 3, title: "Hash Map Patterns", duration: "28 min", type: "video", completed: true },
          { id: 4, title: "Problem Set #1", duration: "60 min", type: "assignment", completed: true },
        ],
      },
      {
        id: 2,
        title: "Trees & Graphs",
        description: "Traversal, search, and dynamic programming on graphs.",
        lessons: [
          { id: 5, title: "Binary Trees & BST", duration: "40 min", type: "video", completed: true },
          { id: 6, title: "Graph Traversal (BFS/DFS)", duration: "38 min", type: "video", completed: true },
          { id: 7, title: "Dijkstra & Shortest Paths", duration: "45 min", type: "video", completed: true },
          { id: 8, title: "Final Assessment", duration: "90 min", type: "quiz", completed: true },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "Node.js Backend Engineering",
    instructor: "Liam O'Brien",
    category: "Backend Development",
    progress: 5,
    totalLessons: 48,
    completedLessons: 2,
    accent: "#FDE68A",
    badge: "Just Started",
    lastAccessed: "1 week ago",
    modules: [
      {
        id: 1,
        title: "Node.js Internals",
        description: "Event loop, libuv, and async internals.",
        lessons: [
          { id: 1, title: "How Node.js Really Works", duration: "32 min", type: "video", completed: true },
          { id: 2, title: "Event Loop Deep Dive", duration: "28 min", type: "video", completed: true },
          { id: 3, title: "Streams & Buffers", duration: "25 min", type: "video", completed: false },
          { id: 4, title: "Worker Threads", duration: "22 min", type: "reading", completed: false },
        ],
      },
      {
        id: 2,
        title: "Building REST APIs",
        description: "Express, middleware, auth, and testing.",
        lessons: [
          { id: 5, title: "Express Architecture Patterns", duration: "30 min", type: "video", completed: false },
          { id: 6, title: "JWT Authentication", duration: "35 min", type: "video", completed: false },
          { id: 7, title: "API Testing with Jest", duration: "40 min", type: "assignment", completed: false },
        ],
      },
    ],
  },
];